<a href="https://colab.research.google.com/github/JamKia/Pandas-1/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
myList=[1,2,3]
newList=[myList,myList]
myDataframe=pd.DataFrame(newList,columns=['r','j','a'])
print(myDataframe)

   r  j  a
0  1  2  3
1  1  2  3


In [ ]:
import pandas as pd
import numpy as np
myDict={'key3':['!',np.nan],'key1':['k','?'],'key5':['2',np.nan]}
myDataframe=pd.DataFrame(myDict,index=[1,2])
print('\n myDataframe:\n',myDataframe)
print('\n isnull:\n',myDataframe.isnull())
print("\n myDataframe['key1'].isnull():\n",myDataframe['key1'].isnull())
print("\n myDataframe['key3'].isnull():\n",myDataframe['key3'].isnull())
print("\n myDataframe['key5'].isnull():\n",myDataframe['key5'].fillna('R'))


 myDataframe:
   key1 key3 key5
1    k    !    2
2    ?  NaN  NaN

 isnull:
     key1   key3   key5
1  False  False  False
2  False   True   True

 myDataframe['key1'].isnull():
 1    False
2    False
Name: key1, dtype: bool

 myDataframe['key3'].isnull():
 1    False
2     True
Name: key3, dtype: bool

 myDataframe['key5'].isnull():
 1    2
2    R
Name: key5, dtype: object


In [ ]:
array=np.array(   [[100, 90, np.nan, 95],[30, np.nan, 45, 56],[52, 40, 80, 98],[np.nan, np.nan, np.nan, 65]]    )

myDataframe=pd.DataFrame(array,columns=['First Score','Fourth Score','Second Score','Third Score'])
print(myDataframe)
myDataframe.dropna(how = 'any',axis=0,inplace=True) #defualt axis=0 ===> row,     how = 'all' or  'any'
print("myDataframe:\n",myDataframe)
print("\n dropna:\n",myDataframe.dropna(axis=1))

   First Score  Fourth Score  Second Score  Third Score
0        100.0          90.0           NaN         95.0
1         30.0           NaN          45.0         56.0
2         52.0          40.0          80.0         98.0
3          NaN           NaN           NaN         65.0
myDataframe:
    First Score  Fourth Score  Second Score  Third Score
2         52.0          40.0          80.0         98.0

 dropna:
    First Score  Fourth Score  Second Score  Third Score
2         52.0          40.0          80.0         98.0


In [ ]:
myDataframe

First Score  Fourth Score  Second Score  Third Score
2         52.0          40.0          80.0         98.0

In [ ]:
df=pd.DataFrame()
df['r']=[100, 90, np.nan, 95]
df['j']=[30, np.nan, 45, 56]
df['r1']=[100, 90, np.nan, 95]

In [ ]:
df=df[['r','r1']].mul(2) #there does not exist 'inplace' parameter
# so as bottom of this url: https://www.geeksforgeeks.org/python-pandas-dataframe/
df

r     r1
0  200.0  200.0
1  180.0  180.0
2    NaN    NaN
3  190.0  190.0

In [ ]:
df1 = pd.DataFrame({"A":[1, 5, 3, 4, 2], 
                    "B":[3, 2, 4, 3, 4], 
                    "C":[2, 2, 7, 3, 4], 
                    "D":[4, 3, 6, 12, 7]},  
                    index =["A1", "A2", "A3", "A4", "A5"])
df2 = pd.DataFrame({"A":[10, 11, 7, 8, 5], 
                    "B":[21, 5, 32, 4, 6],  
                    "C":[11, 21, 23, 7, 9], 
                    "D":[1, 5, 3, 8, 6]}, 
                    index =["A1", "A2", "A3", "A4", "A5"])
# subtract df2 from df1 
print("\n df1.sub(df2):\n",df1.sub(df2))
print("\n df1.mul(df2):\n",df1.mul(df2))
print("\n df1.add(df2):\n",df1.add(df2))
print("\n df1.div(df2):\n",df1.div(df2))
print("\n df1.pow(df2):\n",df1.pow(df2))
print("\n np.log(df1):\n",np.log(df1)) #ln
print("\n np.log10(df1):\n",np.log(df1)) #log10




 df1.sub(df2):
     A   B   C  D
A1 -9 -18  -9  3
A2 -6  -3 -19 -2
A3 -4 -28 -16  3
A4 -4  -1  -4  4
A5 -3  -2  -5  1

 df1.mul(df2):
      A    B    C   D
A1  10   63   22   4
A2  55   10   42  15
A3  21  128  161  18
A4  32   12   21  96
A5  10   24   36  42

 df1.add(df2):
      A   B   C   D
A1  11  24  13   5
A2  16   7  23   8
A3  10  36  30   9
A4  12   7  10  20
A5   7  10  13  13

 df1.div(df2):
            A         B         C         D
A1  0.100000  0.142857  0.181818  4.000000
A2  0.454545  0.400000  0.095238  0.600000
A3  0.428571  0.125000  0.304348  2.000000
A4  0.500000  0.750000  0.428571  1.500000
A5  0.400000  0.666667  0.444444  1.166667

 df1.pow(df2):
            A            B                    C          D
A1         1  10460353203                 2048          4
A2  48828125           32              2097152        243
A3      2187            0  8922003266371364727        216
A4     65536           81                 2187  429981696
A5        32         4096

In [ ]:
print("\n df1['A'].std():\n",df1['A'].std())
print("\n df1.std():\n",df1.std()) #on each columns
print("\n df1.std(axis=1):\n",df1.std(axis=1)) #on each row
print("\n df1.values:",type(df1.values),"\n",df1.values)

print("\n df1.columns:",type(list(df1.columns)),"\n",list(df1.columns))
print("\n df1.index:\n",df1.index)
print("\n df1.sample(frac =.25):\n",df1.sample(frac =.5))
print("\n df1.sample(frac =.25):\n",df1.sample(frac =.5))


 df1['A'].std():
 1.5811388300841898

 df1.std():
 A    1.581139
B    0.836660
C    2.073644
D    3.507136
dtype: float64

 df1.std(axis=1):
 A1    1.290994
A2    1.414214
A3    1.825742
A4    4.358899
A5    2.061553
dtype: float64

 df1.values: <class 'numpy.ndarray'> 
 [[ 1  3  2  4]
 [ 5  2  2  3]
 [ 3  4  7  6]
 [ 4  3  3 12]
 [ 2  4  4  7]]

 df1.columns: <class 'list'> 
 ['A', 'B', 'C', 'D']

 df1.index:
 Index(['A1', 'A2', 'A3', 'A4', 'A5'], dtype='object')

 df1.sample(frac =.25):
     A  B  C  D
A5  2  4  4  7
A3  3  4  7  6

 df1.sample(frac =.25):
     A  B  C   D
A1  1  3  2   4
A4  4  3  3  12


In [ ]:
np.reshape(np.arange(18),(3,6)).T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [ ]:
dfl = pd.DataFrame(np.random.randn(5, 4), columns=list('ABCD'))
print(dfl)
print('\n dfl.iloc[0]:\n',dfl.iloc[0])
print('\n dfl.iloc[0:2,1:3]:\n',dfl.iloc[0:2,1:3])
print('\n dfl.iloc[0:2,1]:\n',dfl.iloc[0:2,1])
print('\n dfl.iloc[:, 2:4]:\n',dfl.iloc[:, 2:4])
print('\n dfl.iloc[[3,4],[0,1]]:\n',dfl.iloc[[3,4],[0,1]])



          A         B         C         D
0 -0.119613 -0.369256 -0.666632 -0.070072
1 -1.919020 -1.720718 -0.830660 -0.327970
2  0.394250 -0.584913 -2.225512  2.030059
3 -1.200455  0.703438 -0.204490  0.349245
4 -0.336101 -0.443095 -0.668328 -1.123287

 dfl.iloc[0]:
 A   -0.119613
B   -0.369256
C   -0.666632
D   -0.070072
Name: 0, dtype: float64

 dfl.iloc[0:2,1:3]:
           B         C
0 -0.369256 -0.666632
1 -1.720718 -0.830660

 dfl.iloc[0:2,1]:
 0   -0.369256
1   -1.720718
Name: B, dtype: float64

 dfl.iloc[:, 2:4]:
           C         D
0 -0.666632 -0.070072
1 -0.830660 -0.327970
2 -2.225512  2.030059
3 -0.204490  0.349245
4 -0.668328 -1.123287

 dfl.iloc[[3,4],[0,1]]:
           A         B
3 -1.200455  0.703438
4 -0.336101 -0.443095


In [ ]:
dfl[(dfl['A'] > 0.5) | (dfl['A'] < -0.5)]

A         B        C         D
1 -1.919020 -1.720718 -0.83066 -0.327970
3 -1.200455  0.703438 -0.20449  0.349245

In [ ]:
dfl[df2[1:4] > 0] = 3
print(dfl)

          A         B         C         D
0 -0.119613 -0.369256 -0.666632 -0.070072
1 -1.919020 -1.720718 -0.830660 -0.327970
2  0.394250 -0.584913 -2.225512  2.030059
3 -1.200455  0.703438 -0.204490  0.349245
4 -0.336101 -0.443095 -0.668328 -1.123287


In [ ]:
df = pd.DataFrame(np.random.rand(10, 3), columns=list('abc'))
print('\n df:\n',df)
print("\n df[(df.a < df.b) & (df.b < df.c)] :\n",df[(df.a < df.b) & (df.b < df.c)])
print("\n df.query('(a < b) & (b < c)') :\n",df.query('(a < b) & (b < c)'))



 df:
           a         b         c
0  0.473314  0.085793  0.579380
1  0.223246  0.020607  0.076857
2  0.404755  0.172245  0.189893
3  0.348797  0.430974  0.364670
4  0.480736  0.046498  0.789599
5  0.407059  0.730813  0.992191
6  0.939717  0.805005  0.130001
7  0.750264  0.782357  0.240581
8  0.833855  0.263999  0.438952
9  0.241115  0.031652  0.879827

 df[(df.a < df.b) & (df.b < df.c)] :
           a         b         c
5  0.407059  0.730813  0.992191

 df.query('(a < b) & (b < c)') :
           a         b         c
5  0.407059  0.730813  0.992191


In [ ]:
import pandas as pd
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'], 
        'age': [42, 52, 36, 24, 73], 
        'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'city'])
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [ ]:
city_to_state = { 'San Francisco' : 'California', 
                  'Baltimore' : 'Maryland', 
                  'Miami' : 'Florida', 
                  'Douglas' : 'Arizona', 
                  'Boston' : 'Massachusetts'}

In [ ]:
df['state'] = df['city'].map(city_to_state)
df

first_name last_name  age           city          state
0      Jason    Miller   42  San Francisco     California
1      Molly  Jacobson   52      Baltimore       Maryland
2       Tina       Ali   36          Miami        Florida
3       Jake    Milner   24        Douglas        Arizona
4        Amy     Cooze   73         Boston  Massachusetts

In [ ]:

list_a = [21, 50, 20]
list_b = [10, 20, 30]
print( list(map(lambda x, y: x + y, list_a, list_b)) ) 


def FUNC_if_greater2x(a,b):
  if a>2*b:
    print(a)
  else: print(b)
    
X= list(map(FUNC_if_greater2x, list_a, list_b))
print(X)


[31, 70, 50]
21
50
30
[None, None, None]


In [ ]:
import pandas as pd

series_a = pd.Series([21, 50, 20])
series_b = pd.Series([10, 20, 30])
print( list(map(lambda x, y: x + y, series_a, series_b)) ) 


def FUNC_if_greater2x(a,b):
  if a>2*b:
    print(a)
  else: print(b)
    
X= list(map(FUNC_if_greater2x, series_a, series_b))
print(X)


[31, 70, 50]
21
50
30
[None, None, None]


In [ ]:
import numpy as np

df = pd.DataFrame(np.random.rand(4, 3), columns=list('abc'))
print(df)

print(df.loc[0,:]+ df.loc[1,:])

print( list(map(lambda x, y: x + y, df.loc[0,:], df.loc[1,:])) ) 

series_a = df.loc[0,:]
series_b = df.loc[1,:]

def FUNC_if_max(a,b):
  if a > b:
    print(a)
    max = a
  else:
    print(b)
    max = b
  return max
  
X= list(map(FUNC_if_max, series_a, series_b))
print(X)

          a         b         c
0  0.386740  0.154857  0.629923
1  0.324738  0.971237  0.469638
2  0.502906  0.156428  0.974696
3  0.918576  0.523155  0.292797
a    0.711478
b    1.126094
c    1.099561
dtype: float64
[0.7114781463264074, 1.1260940931768229, 1.099561283289273]
0.3867404320725132
0.9712374891163118
0.6299228502067459
[0.3867404320725132, 0.9712374891163118, 0.6299228502067459]


In [ ]:
list(filter(lambda df : df.loc[0,:] > 0 , df.loc[0,:])) 


TypeError: ignored

In [ ]:
dict_a = [{'name': 'python', 'points': 10}, {'name': 'java', 'points': 8}]

list(filter(lambda x : x['name'] == 'python', dict_a)) # Output: [{'name': 'python', 'points': 10}]


[{'name': 'python', 'points': 10}]

In [ ]:
def rule(x, y):
    if x == 'high' and y > 10:
         return 1
    else:
         return 0
      
      
import pandas as pd

df = pd.DataFrame({ 'c1':[ 'high' ,'high', 'low', 'low'], 'c2': [0, 23, 17, 4]})
df['new'] = df.apply(lambda x: rule(x['c1'], x['c2']), axis =  1)
print(df.head())
print("------------------------\n")
print( df[ (df.loc[:,'c1'] == 'high') & (df.loc[:,'c2'] > 10) ] )
print("------------------------\n")
print( df['c1'].value_counts().reset_index().sort_values(by='index'))
print("------------------------\n")
print(df['c1'].value_counts())
print("------------------------\n")


"""You have a numerical column, and would like to classify the values 
in that column into groups, say top 5% into group 1, 5–20% into group 2,
20%-50% into group 3, bottom 50% into group 4. Of course, you can do it
with pandas.cut, but I’d like to provide another option here:"""
"""pandas.cut: "https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.cut.html"  """

import numpy as np
cut_points = [np.percentile(df['c2'], i) for i in [50, 80, 95]]
print("cut_points:\t",cut_points)
df['group'] = 1
for i in range(3):
    print(i)
    df['group'] = df['group'] + (df['c2'] <= cut_points[i])
# or <= cut_points[i]
print(df)

     c1  c2  new
0  high   0    0
1  high  23    1
2   low  17    0
3   low   4    0
------------------------

     c1  c2  new
1  high  23    1
------------------------

  index  c1
0  high   2
1   low   2
------------------------

high    2
low     2
Name: c1, dtype: int64
------------------------

cut_points:	 [10.5, 19.400000000000002, 22.099999999999994]
0
1
2
     c1  c2  new  group
0  high   0    0      4
1  high  23    1      1
2   low  17    0      3
3   low   4    0      4


In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({ 'id': ['A001','C022',2], 'c1':[0,0,np.nan], 'c2': [np.nan,1,1]})
df = df[['id', 'c1', 'c2']]
df['num_nulls'] = df[['c1', 'c2']].isnull().sum(axis=1)
print(df.head())

df_filter = df['id'].isin(['A001','C022',...])
print("------------------------\n")
print(df[df_filter])

     id   c1   c2  num_nulls
0  A001  0.0  NaN          1
1  C022  0.0  1.0          0
2     2  NaN  1.0          1
------------------------

     id   c1   c2  num_nulls
0  A001  0.0  NaN          1
1  C022  0.0  1.0          0


In [ ]:
from copy import deepcopy
df2 = deepcopy(df1)

In [ ]:
df['maximum'] = df[['c1','c2']].max(axis =1) #fast
df['maximum'] = df.apply(lambda x: max(x['c1'], x['c2']), axis = 1) #slow